# mysql
export MYSQL_DB_HOST=
export MYSQL_DB_PORT=
export MYSQL_DB_NAME=
export MYSQL_DB_USER=
export MYSQL_DB_PASSWORD=

# mongodb
export MONGO_DB_HOST=
export MONGO_DB_PORT=
export MONGO_DB_NAME=
export MONGO_DB_USER=
export MONGO_DB_PASSWORD=

# minio new env
export MINIO_INTERNAL_ENDPOINT=
export MINIO_PUBLIC_ENDPOINT=
export MINIO_ACCESS_KEY=
export MINIO_SECRET_KEY=
export MINIO_BUCKET=iva

# kafka
export KAFKA_BOOTSTRAP_SERVER=

# milvus
export MILVUS_HOST=
export MILVUS_PORT=

# redis
export REDIS_HOST=
export REDIS_PORT=
export REDIS_SENTINEL=
export REDIS_MASTER_GROUP_NAME=
export REDIS_AUTH=

# internal services
export SEARCH_SERVICE=
export AI_SERVICE=
export VMS_MANAGER_SERVICE=
export RESTREAM_SERVICE=
export DETECTOR_SERVICE=

export WATCHLIST_SERVICE=
export DASHBOARD_SERVICE=

export API_KEY_WEB_SERVICE=
export API_KEY_DASHBOARD_SERVICE=
export API_KEY_WATCHLIST_SERVICE=
export API_KEY_MK=
export API_KEY_VMS_MANAGER_SERVICE=
export API_KEY_AI_SERVICE=

export JWT_SECRET=

export CORS_ALLOWED_ORIGINS="http://localhost:3000,http://127.0.0.1:3000"
export DEBUG=1
