# Generated by Django 4.2.17 on 2024-12-30 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
