# Generated by Django 4.2.17 on 2025-01-07 10:51

import apps.khanhvan.models.camera
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.BigIntegerField(null=True)),
                ('updated_by', models.BigIntegerField(null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('desc', models.CharField(blank=True, default='', max_length=512)),
                ('active', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'camera_group',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.BigIntegerField(null=True)),
                ('updated_by', models.BigIntegerField(null=True)),
                ('deleted_at', models.BigIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(blank=True, default='', max_length=1024)),
                ('url', models.CharField(blank=True, default='', max_length=255)),
                ('background_url', models.CharField(blank=True, default='', max_length=255)),
                ('background_width', models.IntegerField(default=0, null=True)),
                ('background_height', models.IntegerField(default=0, null=True)),
                ('conn_status', models.IntegerField(default=apps.khanhvan.models.camera.ConnStatus['NOT_CONNECT'], null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cameras', to='khanhvan.cameragroup')),
            ],
            options={
                'db_table': 'camera',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='camera',
            constraint=models.UniqueConstraint(fields=('name', 'deleted_at'), name='unique_active_camera_name'),
        ),
    ]
