# Generated by Django 4.2.17 on 2025-01-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khanhvan', '0002_cameraalert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cameraalert',
            options={'managed': True},
        ),
    ]
