# Generated by Django 4.2.17 on 2025-01-22 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('khanhvan', '0004_alter_cameraalert_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'rule',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RuleCamera',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.BigIntegerField(null=True)),
                ('updated_by', models.BigIntegerField(null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rule_configs', to='khanhvan.camera')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='camera_configs', to='khanhvan.rule')),
            ],
            options={
                'db_table': 'rule_camera',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='rule',
            name='cameras',
            field=models.ManyToManyField(related_name='rules', through='khanhvan.RuleCamera', to='khanhvan.camera'),
        ),
    ]
