# Generated by Django 4.2.17 on 2025-02-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khanhvan', '0006_rule_end_time_rule_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
