# Generated by Django 4.2.17 on 2025-02-07 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('khanhvan', '0007_alter_rule_end_time_alter_rule_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='current_version',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='RuleVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('version_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(default=0)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='khanhvan.rule')),
            ],
            options={
                'db_table': 'rule_version',
                'managed': True,
            },
        ),
    ]
