# Generated by Django 4.2.17 on 2025-02-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khanhvan', '0008_rule_current_version_ruleversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='created_by',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='updated_by',
            field=models.BigIntegerField(null=True),
        ),
    ]
