# Generated by Django 4.2.17 on 2025-02-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khanhvan', '0009_rule_created_by_rule_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleversion',
            name='created_by',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ruleversion',
            name='updated_by',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='ruleversion',
            constraint=models.UniqueConstraint(fields=('rule', 'version_number'), name='unique_rule_version'),
        ),
    ]
