# Generated by Django 4.2.17 on 2025-02-12 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khanhvan', '0010_ruleversion_created_by_ruleversion_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cameraalert',
            options={'managed': True},
        ),
    ]
