# Generated by Django 4.2.17 on 2025-02-12 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khanhvan', '0011_alter_cameraalert_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cameraalert',
            options={'managed': False},
        ),
    ]
