# Generated by Django 4.2.17 on 2025-03-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khanhvan', '0012_alter_cameraalert_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AImodel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.BigIntegerField(null=True)),
                ('updated_by', models.BigIntegerField(null=True)),
                ('aimodel_name', models.CharField(max_length=255)),
                ('aimodel_apikey', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'ai_model',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RulePrompt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.BigIntegerField(null=True)),
                ('updated_by', models.BigIntegerField(null=True)),
                ('prompt', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'rule_prompt',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='rulecamera',
            constraint=models.UniqueConstraint(fields=('rule', 'camera'), name='unique_rule_camera'),
        ),
    ]
