# Generated by Django 4.2.17 on 2025-03-05 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khanhvan', '0014_aimodel_aimodel_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AImodel',
            new_name='VLMModel',
        ),
        migrations.AlterModelTable(
            name='vlmmodel',
            table='vlm_model',
        ),
    ]
