# Generated by Django 4.2.17 on 2025-03-05 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khanhvan', '0015_rename_aimodel_vlmmodel_alter_vlmmodel_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vlmmodel',
            old_name='aimodel_apikey',
            new_name='vlmmodel_apikey',
        ),
        migrations.RenameField(
            model_name='vlmmodel',
            old_name='aimodel_name',
            new_name='vlmmodel_name',
        ),
        migrations.RenameField(
            model_name='vlmmodel',
            old_name='aimodel_url',
            new_name='vlmmodel_url',
        ),
    ]
