# Generated by Django 4.2.17 on 2025-03-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khanhvan', '0016_rename_aimodel_apikey_vlmmodel_vlmmodel_apikey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='type',
            field=models.IntegerField(choices=[(0, 'Scene Change'), (1, 'Prompt-based Detection')], default=0),
        ),
        migrations.AlterField(
            model_name='vlmmodel',
            name='vlmmodel_apikey',
            field=models.TextField(),
        ),
    ]
