# Generated by Django 4.2.17 on 2025-03-05 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('khanhvan', '0017_rule_prompt_alter_rule_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='vlm_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='khanhvan.vlmmodel'),
        ),
    ]
