# Generated by Django 4.2.17 on 2025-03-06 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('khanhvan', '0018_rule_vlm_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.BigIntegerField(null=True)),
                ('updated_by', models.BigIntegerField(null=True)),
                ('describe', models.TextField()),
            ],
            options={
                'db_table': 'prompt',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='RulePrompt',
        ),
        migrations.AlterField(
            model_name='rule',
            name='prompt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='khanhvan.prompt'),
        ),
    ]
