# Generated by Django 4.2.17 on 2025-03-06 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khanhvan', '0019_prompt_delete_ruleprompt_alter_rule_prompt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompt',
            old_name='describe',
            new_name='content',
        ),
    ]
