# Generated by Django 4.2.17 on 2025-03-07 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khanhvan', '0020_rename_describe_prompt_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'managed': False},
        ),
    ]
