# Generated by Django 4.2.17 on 2025-03-07 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khanhvan', '0021_alter_rule_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'managed': True},
        ),
    ]
