# Generated by Django 4.2.17 on 2025-03-07 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('khanhvan', '0022_alter_rule_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vlmmodel',
            old_name='vlmmodel_apikey',
            new_name='apikey',
        ),
        migrations.RenameField(
            model_name='vlmmodel',
            old_name='vlmmodel_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='vlmmodel',
            old_name='vlmmodel_url',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='rule',
            name='prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='khanhvan.prompt'),
        ),
    ]
