# Generated by Django 4.2.17 on 2025-03-07 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khanhvan', '0023_rename_vlmmodel_apikey_vlmmodel_apikey_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vlmmodel',
            old_name='apikey',
            new_name='api_key',
        ),
    ]
