# Generated by Django 4.2.17 on 2025-03-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khanhvan', '0025_alter_rule_prompt_alter_rule_vlm_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlmmodel',
            name='code_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vlmmodel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
