# Generated by Django 4.2.17 on 2025-03-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khanhvan', '0026_vlmmodel_code_name_alter_vlmmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='system',
            field=models.TextField(blank=True, default=''),
        ),
    ]
