# Generated by Django 4.2.17 on 2025-03-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khanhvan', '0027_prompt_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='system',
            field=models.TextField(blank=True, default='You are a personal assistant'),
        ),
    ]
