# Generated by Django 4.2.17 on 2025-03-11 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khanhvan', '0028_alter_prompt_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlmmodel',
            name='api_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
