global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'minio-job'
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets: ['minio:9000']
  - job_name: 'minio-cold-job'
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets: [ 'minio-cold:9000' ]
  - job_name: 'minio-cold-replica-job'
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets: [ 'minio-cold-replica:9000' ]
